truenas/zettarepl

integration-tests/replication/test_preserves_deleted_datasets.py
zettarepl/transport/ssh_netcat_helper.py
zettarepl/transport/zfscli/__init__.py

Just found out this was never pushed and merged. Can't find corresponding issue in redmine, but newly introduces test looks sane and passes.

Add integration-tests/replication/test_preserves_deleted_datasets.py

---

README.md
integration-tests/replication/test_preserves_clone_origin.py
tests/replication/test_run.py
zettarepl/definition/schema/replication-task.schema.yaml
zettarepl/replication/run.py
zettarepl/replication/task/task.py
zettarepl/transport/interface.py
zettarepl/transport/local.py
zettarepl/transport/ssh.py
zettarepl/transport/ssh_netcat.py
zettarepl/transport/ssh_netcat_helper.py
zettarepl/transport/zfscli/__init__.py

@william-gr this is to resolve https://jira.ixsystems.com/browse/NAS-100135
We may safely ship this zettarepl with 11.3 (new option will be disabled by default) but delay adding new checkbox to middleware/UI until 12.

Add ability to replicate entire filesystem (in order to preserve clone origins)

---

integration-tests/replication/test_target_without_snapshots_but_with_data.py
zettarepl/dataset/data.py
zettarepl/replication/run.py
zettarepl/transport/zfscli/__init__.py
zettarepl/transport/zfscli/parse.py

git cherry-pick -x 4b12f02c557771bac4671ae9a55f3dfd9d5b69cb

NAS-105409 / 11.3 / Implement proper way of checking if destination has data (by themylogin)

---

integration-tests/retention/test_local_retention.py
integration-tests/retention/test_remote_retention.py
tests/retention/test_calculate.py
zettarepl/retention/calculate.py

git cherry-pick -x 645c9dd2f81acbcb1c166ece9fdf2367f6fe7e0c

NAS-106517 / 11.3 / Do not remove the only snapshot left (by themylogin)

---

integration-tests/transport/test_ssh_authentication_error.py
zettarepl/replication/run.py

…able errors as they often happen when remote host is rebooting

NAS-106780 / 12.1 / Treat most of the paramiko errors (e.g. SSH banner errors) as recover… (by themylogin)

---

zettarepl/transport/local.py
zettarepl/transport/progress_report_mixin.py
zettarepl/transport/ssh.py

git cherry-pick -x a05e3dc232238dfac0f103c42c78c54262c0f185
Original PR: https://github.com/freenas/zettarepl/pull/111

NAS-107411 / 11.3 / Report zfs send progress for local replication (by themylogin)

---

integration-tests/replication/test_data_progress.py
integration-tests/replication/test_progress.py
zettarepl/dataset/data.py
zettarepl/dataset/list.py
zettarepl/observer.py
zettarepl/replication/dataset_size_observer.py
zettarepl/replication/run.py
zettarepl/transport/local.py
zettarepl/transport/ssh.py
zettarepl/transport/ssh_netcat.py
zettarepl/transport/zfscli/__init__.py
zettarepl/transport/zfscli/exception.py

@william-gr I believe it's too much changes to be backported into 11.3?

NAS-107317 / 20.10 / Replication data transfer progress

---

integration-tests/retention/test_zfs_clone.py
zettarepl/snapshot/destroy.py

snapshot.destroy: deal with cloned snapshots

---

integration-tests/retention/test_zfs_clone.py
zettarepl/snapshot/destroy.py

Fixes #127 
Original PR: https://github.com/freenas/zettarepl/pull/128

NAS-108307 / 11.3 / snapshot.destroy: deal with cloned snapshots (by rkojedzinszky)

---

zettarepl/replication/run.py

NAS-108578 / 20.12 / Do not mount datasets with "noauto" mount property

---

integration-tests/replication/test_zvol_replication.py
zettarepl/transport/zfscli/exception.py

…roy an encrypted filesystem"
Original PR: https://github.com/truenas/zettarepl/pull/159
Jira URL: https://jira.ixsystems.com/browse/NAS-109979

NAS-109979 / 21.06 / Provide better explanation for "zfs receive -F cannot be used to dest… (by themylogin)

---

integration-tests/replication/test_readonly.py
zettarepl/replication/run.py

…o an existing non-readonly zvol
Original PR: https://github.com/truenas/zettarepl/pull/160
Jira URL: https://jira.ixsystems.com/browse/NAS-108451

NAS-108451 / 12.0 / Better error message when replication a zvol with readonly: require t… (by themylogin)

---

tests/replication/test_stuck.py
zettarepl/replication/run.py
zettarepl/replication/stuck.py

git cherry-pick -x 22ae2757627724d2d78f3c52bc04076723f0b8e0
Original PR: https://github.com/truenas/zettarepl/pull/161
Jira URL: https://jira.ixsystems.com/browse/NAS-110038

NAS-110038 / 12.0 / Allow destination to catch up with partially-complete state after killing stuck replication (by themylogin)

---

tests/utils/test_shlex.py
zettarepl/transport/interface.py
zettarepl/utils/shlex.py

… cut strings
Original PR: https://github.com/truenas/zettarepl/pull/176
Jira URL: https://jira.ixsystems.com/browse/NAS-110976

NAS-110976 / 12.0 / Print full shell pipe commands in the debug instead of obfuscated and… (by themylogin)

---

integration-tests/replication/test_name_regex.py
zettarepl/replication/snapshots_to_send.py

…ts to send
Original PR: https://github.com/truenas/zettarepl/pull/178
Jira URL: https://jira.ixsystems.com/browse/NAS-111043

NAS-111043 / 21.06-BETA.1 / Fix get_snapshots_to_send_with_name_pattern when there are no snapsho… (by themylogin)

---

integration-tests/replication/test_name_regex.py
integration-tests/replication/test_replicate.py
zettarepl/replication/most_recent_snapshot.py
zettarepl/replication/run.py
zettarepl/replication/snapshots_to_send.py

git cherry-pick -x 5010f145d337a1026cf6c8c1fb29eb5e9f940e2c
Original PR: https://github.com/truenas/zettarepl/pull/187
Jira URL: https://jira.ixsystems.com/browse/NAS-111782

NAS-111782 / 21.10 / Check "no snapshots to send" for full replication, zfs send -R is not atomic and might fool us (by themylogin)

---

README.md
integration-tests/replication/test_replicate.py
zettarepl/transport/ssh.py

git cherry-pick -x 1073997c5138b594af12b47b04d60bdbea8d0337
Original PR: https://github.com/truenas/zettarepl/pull/197
Jira URL: https://jira.ixsystems.com/browse/NAS-113397

NAS-113397 / 13.0 / Make `client_loop: send disconnect: Broken pipe` recoverable replication error (by themylogin)

---

integration-tests/replication/test_name_regex.py
zettarepl/replication/task/task.py

NOTE: Not considered blocker for `22.02-RC`
Reverts truenas/zettarepl#203

Revert "NAS-113890 / 22.02-RC.2 / Fix KeyError: 'naming-schema' (by themylogin)"

---

integration-tests/replication/test_name_regex.py
zettarepl/replication/task/task.py

NAS-113890 / 22.02-RC.2 / Fix KeyError: 'naming-schema' (by themylogin)

---

integration-tests/replication/test_data_progress.py
integration-tests/replication/test_parallel_replication.py
integration-tests/replication/test_pre_retention.py
integration-tests/replication/test_preserves_deleted_datasets.py
integration-tests/replication/test_progress.py
integration-tests/replication/test_push_replication.py
integration-tests/replication/test_replication_retry.py
integration-tests/replication/test_snapshot_gone.py
integration-tests/transport/test_ssh_authentication_error.py
zettarepl/replication/pre_retention.py
zettarepl/replication/run.py
zettarepl/replication/snapshots_to_send.py
zettarepl/replication/task/snapshot_owner.py
zettarepl/utils/test.py
zettarepl/zettarepl.py

@rick-mesta this seems to be too much of a change for 13.0, should we move this to 22.02?

NAS-111800 / 22.02 / Perform destination retention before replication in order to free up disk space / quotas

---

tests/replication/task/test_snapshot_owner.py
zettarepl/replication/task/snapshot_owner.py

… be removed by retention
Original PR: https://github.com/truenas/zettarepl/pull/220
Jira URL: https://jira.ixsystems.com/browse/NAS-114898

NAS-114898 / 13.0 / Fix `hold_pending_snapshots` feature allowing for incremental base to… (by themylogin)

---

integration-tests/replication/test_dataset_gone.py
zettarepl/transport/ssh_netcat_helper.py
zettarepl/transport/zfscli/exception.py

…replication
Original PR: https://github.com/truenas/zettarepl/pull/230
Jira URL: https://jira.ixsystems.com/browse/NAS-115938

NAS-115938 / 22.02.2 / Do not crash when source dataset was destroyed during the SSH+NETCAT … (by themylogin)

---

integration-tests/replication/test_dataset_gone.py
zettarepl/transport/ssh_netcat_helper.py
zettarepl/transport/zfscli/exception.py

git cherry-pick -x 399369782c76fb12acc3ee0a23c28b2bbfa84721
…replication
Original PR: https://github.com/truenas/zettarepl/pull/230
Jira URL: https://jira.ixsystems.com/browse/NAS-115938

NAS-115938 / 13.0 / Do not crash when source dataset was destroyed during the SSH+NETCAT … (by themylogin)

---

zettarepl/replication/run.py

…external code once we add a new dataset property
Original PR: https://github.com/truenas/zettarepl/pull/236
Jira URL: https://jira.ixsystems.com/browse/NAS-115977

NAS-115977 / 13.0 / Add `ReplicationContext.remove_dataset` so we don't forget to update … (by themylogin)

---

zettarepl/replication/run.py

…external code once we add a new dataset property
Original PR: https://github.com/truenas/zettarepl/pull/236
Jira URL: https://jira.ixsystems.com/browse/NAS-115977

NAS-115977 / 22.02.2 / Add `ReplicationContext.remove_dataset` so we don't forget to update … (by themylogin)

---

integration-tests/replication/test_pre_retention.py
zettarepl/dataset/list.py

…ith_properties`
Original PR: https://github.com/truenas/zettarepl/pull/241
Jira URL: https://jira.ixsystems.com/browse/NAS-116279

NAS-116279 / 22.02.2 / Do not include unrelated datasets into non-recursive `list_datasets_w… (by themylogin)

---

tests/test_zettarepl.py
zettarepl/zettarepl.py

…ltiple source datasets
Original PR: https://github.com/truenas/zettarepl/pull/262
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121286

NAS-121286 / 22.12.3 / Fix `_replication_tasks_can_run_in_parallel` being too strict with mu… (by themylogin)

---

tests/test_zettarepl.py
zettarepl/zettarepl.py

…ltiple source datasets
Original PR: https://github.com/truenas/zettarepl/pull/262
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121286

NAS-121286 / 13.0 / Fix `_replication_tasks_can_run_in_parallel` being too strict with mu… (by themylogin)

---

README.md
integration-tests/snapshot/test_snapshot_exclude.py
tests/dataset/test_exclude.py
tests/snapshot/test_create.py
zettarepl/dataset/exclude.py
zettarepl/snapshot/create.py
zettarepl/transport/utils.py
zettarepl/zcp/recursive_snapshot_exclude.lua
zettarepl/zcp/render_zcp.py

This implements #245
Let me know if I need to change anything.

Add glob test to exclude

---

zettarepl/transport/base_ssh.py

This PR fixes a fatal memory leak in our TrueNAS CORE setup. I am not 100% sure why it works so let me tell you how I arrived at this.
The TrueNAS server ran out of its 128GB of memory on a monthly basis, fixable only by a reboot. I finally checked it mid-month and noticed a huge `zettarepl` process.
Digging in, zettarepl would start leaking memory some hours after a restart – but not due to any particular job (so there probably is a kind of race involved).
I noticed that whenever the leaking started, `zettarepl` would grow from five to seven permanent threads. The two extra threads were named like `Thread-17428` and `retention.close_shell`.
Hmm, what the heck is a "close shell" thread ... well, it turns out that it was introduced in #166 to fix a replication hang reported in …

NAS-125338 / 23.10.1 / Close stdin/stdout/stderr (by amelchio)

---

zettarepl/transport/ssh_netcat.py
zettarepl/transport/zfscli/exception.py

In the Jira discussion I suggested to prohibit such a configuration, but it is not possible since at the moment of the replication configuration we can't know how sudo is configured on the remote system. The best thing we can do is provide a better error message (I'll also create a doc ticket as discussed).

NAS-125982 / 24.04 / Explain that SSH+NETCAT replication requires passwordless sudo for all commands

---

integration-tests/replication/test_encrypted_target.py
zettarepl/dataset/data.py
zettarepl/replication/run.py

git cherry-pick -x 62f40799bd2089419305b7ce1215f3f4218692f1
If the original PR was merged via a squash, you can just cherry-pick the squashed commit:
git cherry-pick -x 7768bd5f511d9213835d470e70195ae150e02a22
Original PR: https://github.com/truenas/zettarepl/pull/300
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126891

NAS-126891 / 13.1 / `Does not have snapshots` -> `Does not have matching snapshots`` (by themylogin)

---

zettarepl/transport/zfscli/exception.py

Discovered while working on https://ixsystems.atlassian.net/issues/NAS-127984

NAS-128485 / 24.10 / Remove annoying messages from the ZFS error text

---

zettarepl/transport/zfscli/exception.py

Discovered while working on https://ixsystems.atlassian.net/issues/NAS-127984
Original PR: https://github.com/truenas/zettarepl/pull/317
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128485

NAS-128485 / 24.04.1 / Remove annoying messages from the ZFS error text (by themylogin)

---

integration-tests/retention/test_local_retention.py
zettarepl/snapshot/list.py
zettarepl/transport/zfscli/exception.py
zettarepl/zettarepl.py

…not exist
Original PR: https://github.com/truenas/zettarepl/pull/332
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135748

NAS-135748 / 25.04.2 / Do not crash the whole retention process when one of the datasets do … (by themylogin)

---

integration-tests/replication/test_mount.py
zettarepl/definition/schema/replication-task.schema.yaml
zettarepl/replication/run.py
zettarepl/replication/task/task.py
zettarepl/transport/interface.py
zettarepl/transport/local.py
zettarepl/transport/ssh.py
zettarepl/transport/ssh_netcat.py
zettarepl/transport/ssh_netcat_helper.py
zettarepl/transport/zfscli/__init__.py

This option is an equivalent of passing `-u` to `zfs recv`.

NAS-136066 / 25.10 / `mount` option
